spring:
  application:
    name: accounting
  datasource:
    driverClassName: org.h2.Driver
    password: sa
    username: sa
    url: jdbc:h2:mem:rf_industries_accounting
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: 'always'
server:
  port: 4101
  servlet:
    contextPath: /accounting

scheduling:
  syncData: '0 0/30 * * * ?'

commons:
  grpc:
    address: static://localhost:5102
    negotiation-type: plaintext


grpc:
  client:
    taxes:
      address: ${commons.grpc.address}
      negotiation-type: ${commons.grpc.negotiation-type}
    taxesVersions:
      address: ${commons.grpc.address}
      negotiation-type: ${commons.grpc.negotiation-type}

