
INSERT INTO RF_ACCOUNTING_ACCOUNTING
(CODE, NAME, BUSINESS_CUSTOMER_ID, ENTERPRISE_ID)
VALUES ('GNRL', 'General', 1, 1);

INSERT INTO RF_ACCOUNTING_ACCOUNTING_YEARS
(ACCOUNTING_ID, CODE, NAME, START_DATE, END_DATE, BUSINESS_CUSTOMER_ID, ENTERPRISE_ID)
VALUES (1, 2023, '2023', '2023-01-01', '2023-12-31', 1, 1);


