
INSERT INTO RF_ACCOUNTING_ACCOUNTING
(CODE, NAME, BUSINESS_CUSTOMER_ID, ENTERPRISE_ID)
VALUES ('GNRL', 'General', 1, 1);

INSERT INTO RF_ACCOUNTING_ACCOUNTING_YEARS
(ACCOUNTING_ID, CODE, NAME, START_DATE, END_DATE, BUSINESS_CUSTOMER_ID, ENTERPRISE_ID)
VALUES (1, '2023', '2023', '2023-01-01', '2023-12-31', 1, 1);

INSERT INTO RF_ACCOUNTING_SERIES
(ACCOUNTING_ID, ACCOUNTING_YEAR_ID, TYPE, CODE, NUMBER, NAME, BUSINESS_CUSTOMER_ID, ENTERPRISE_ID)
VALUES (1, 1, 1, 'PR', 0, 'PURCHASES', 1, 1);

INSERT INTO RF_ACCOUNTING_SERIES
(ACCOUNTING_ID, ACCOUNTING_YEAR_ID, TYPE, CODE, NUMBER, NAME, BUSINESS_CUSTOMER_ID, ENTERPRISE_ID)
VALUES (1, 1, 2, 'SL', 0, 'SALES', 1, 1);

INSERT INTO RF_ACCOUNTING_SERIES
(ACCOUNTING_ID, ACCOUNTING_YEAR_ID, TYPE, CODE, NUMBER, NAME, BUSINESS_CUSTOMER_ID, ENTERPRISE_ID)
VALUES (1, 1, 3, 'IN', 0, 'INVESTMENT', 1, 1);

INSERT INTO RF_ACCOUNTING_ACCOUNTING_YEARS_SERIES
(ACCOUNTING_YEAR_ID, TYPE, SERIE_ID, BUSINESS_CUSTOMER_ID, ENTERPRISE_ID)
VALUES (1, 1, 1, 1, 1);

INSERT INTO RF_ACCOUNTING_ACCOUNTING_YEARS_SERIES
(ACCOUNTING_YEAR_ID, TYPE, SERIE_ID, BUSINESS_CUSTOMER_ID, ENTERPRISE_ID)
VALUES (1, 2, 2, 1, 1);

INSERT INTO RF_ACCOUNTING_ACCOUNTING_YEARS_SERIES
(ACCOUNTING_YEAR_ID, TYPE, SERIE_ID, BUSINESS_CUSTOMER_ID, ENTERPRISE_ID)
VALUES (1, 3, 3, 1, 1);