
CREATE TABLE IF NOT EXISTS RF_ACCOUNTING_ACCOUNTING(
ID INT AUTO_INCREMENT PRIMARY KEY,
CODE VARCHAR(4) NOT NULL,
NAME VARCHAR(30) NOT NULL,
BUSINESS_CUSTOMER_ID INT NOT NULL,
ENTERPRISE_ID INT NOT NULL,
USER_CREATED_AT_ID INT,
USER_UPDATED_AT_ID INT,
CREATED_AT DATETIME,
UPDATED_AT DATETIME,
CONSTRAINT UQ_ACC_ACC_COD UNIQUE (BUSINESS_CUSTOMER_ID, ENTERPRISE_ID, CODE)
);

CREATE TABLE IF NOT EXISTS RF_ACCOUNTING_ACCOUNTING_YEARS(
ID INT AUTO_INCREMENT PRIMARY KEY,
ACCOUNTING_ID INT NOT NULL,
CODE VARCHAR(4) NOT NULL,
NAME VARCHAR(30) NOT NULL,
START_DATE DATE NOT NULL,
END_DATE DATE NOT NULL,
BUSINESS_CUSTOMER_ID INT NOT NULL,
ENTERPRISE_ID INT NOT NULL,
USER_CREATED_AT_ID INT,
USER_UPDATED_AT_ID INT,
CREATED_AT DATETIME,
UPDATED_AT DATETIME,
FOREIGN KEY (ACCOUNTING_ID) REFERENCES RF_ACCOUNTING_ACCOUNTING(ID),
CONSTRAINT UQ_ACC_YR_COD UNIQUE (ACCOUNTING_ID, CODE)
);

CREATE TABLE IF NOT EXISTS RF_ACCOUNTING_LEDGER_ACCOUNTS(
ID INT AUTO_INCREMENT PRIMARY KEY,
CODE VARCHAR(10) NOT NULL,
NAME VARCHAR(30) NOT NULL,
BUSINESS_CUSTOMER_ID INT NOT NULL,
ENTERPRISE_ID INT NULL,
USER_CREATED_AT_ID INT,
USER_UPDATED_AT_ID INT,
CREATED_AT DATETIME,
UPDATED_AT DATETIME,
CONSTRAINT UQ_ACC_LED_ACC_COD UNIQUE (BUSINESS_CUSTOMER_ID, ENTERPRISE_ID, CODE)
);

CREATE TABLE IF NOT EXISTS RF_ACCOUNTING_INVOICE_HEADERS(
ID INT AUTO_INCREMENT PRIMARY KEY,
TYPE TINYINT NOT NULL,
CODE VARCHAR(6) NOT NULL,
NUMBER INT NOT NULL,
DATE_TIME DATETIME,
ACCOUNTING_ID INT NOT NULL,
ACCOUNTING_YEAR_ID INT NOT NULL,
LEDGER_ACCOUNT_ID INT NOT NULL,
BUSINESS_CUSTOMER_ID INT NOT NULL,
ENTERPRISE_ID INT NOT NULL,
USER_CREATED_AT_ID INT,
USER_UPDATED_AT_ID INT,
CREATED_AT DATETIME,
UPDATED_AT DATETIME,
FOREIGN KEY (ACCOUNTING_ID) REFERENCES RF_ACCOUNTING_ACCOUNTING(ID),
FOREIGN KEY (ACCOUNTING_YEAR_ID) REFERENCES RF_ACCOUNTING_ACCOUNTING_YEARS(ID),
FOREIGN KEY (LEDGER_ACCOUNT_ID) REFERENCES RF_ACCOUNTING_LEDGER_ACCOUNTS(ID),
CONSTRAINT UQ_ACC_INV_HED_COD UNIQUE (ACCOUNTING_ID, ACCOUNTING_YEAR_ID, TYPE, CODE, NUMBER)
);