
CREATE TABLE IF NOT EXISTS RF_ACCOUNTING_ACCOUNTING(
ID INT AUTO_INCREMENT PRIMARY KEY,
CODE VARCHAR(10),
NAME VARCHAR(30),
BUSINESS_CUSTOMER_ID INT NOT NULL,
ENTERPRISE_ID INT NOT NULL,
USER_CREATED_AT_ID INT,
USER_UPDATED_AT_ID INT,
CREATED_AT DATETIME,
UPDATED_AT DATETIME,
CONSTRAINT UQ_ACC_ACC_COD UNIQUE (BUSINESS_CUSTOMER_ID, ENTERPRISE_ID,CODE)
);

CREATE TABLE IF NOT EXISTS RF_ACCOUNTING_ACCOUNTING_YEARS(
ID INT AUTO_INCREMENT PRIMARY KEY,
ACCOUNTING_ID INT NULL,
CODE VARCHAR(4),
NAME VARCHAR(30),
START_DATE DATE NOT NULL,
END_DATE DATE NOT NULL,
BUSINESS_CUSTOMER_ID INT NOT NULL,
ENTERPRISE_ID INT NOT NULL,
USER_CREATED_AT_ID INT,
USER_UPDATED_AT_ID INT,
CREATED_AT DATETIME,
UPDATED_AT DATETIME,
FOREIGN KEY (ACCOUNTING_ID) REFERENCES RF_ACCOUNTING_ACCOUNTING(ID),
CONSTRAINT UQ_ACC_YR_COD UNIQUE (BUSINESS_CUSTOMER_ID, ENTERPRISE_ID,CODE)
);

CREATE TABLE IF NOT EXISTS RF_ACCOUNTING_TAXES(
ID INT AUTO_INCREMENT PRIMARY KEY,
CODE VARCHAR(4),
NAME VARCHAR(30),
BUSINESS_CUSTOMER_ID INT NOT NULL,
ENTERPRISE_ID INT NULL,
USER_CREATED_AT_ID INT,
USER_UPDATED_AT_ID INT,
CREATED_AT DATETIME,
UPDATED_AT DATETIME,
CONSTRAINT UQ_ACC_TX_CD UNIQUE (BUSINESS_CUSTOMER_ID, ENTERPRISE_ID,CODE)
);