spring:
  application:
    name: commons
  datasource:
    driverClassName: org.h2.Driver
    password: sa
    username: sa
    url: jdbc:h2:mem:test
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: 'always'
server:
  port: 4102
  servlet:
    contextPath: /commons

