spring:
  application:
    name: commons
  datasource:
    driverClassName: org.h2.Driver
    password: sa
    username: sa
    url: jdbc:h2:mem:rf_industries_commons
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: 'always'
server:
  port: 4102
  servlet:
    contextPath: /commons

grpc:
  server:
    port: 5102

scheduling:
  syncData: '0 0/30 * * * ?'

