-- taxes
INSERT INTO RF_COMMONS_TAXES
(CODE, NAME, BUSINESS_CUSTOMER_ID, ENTERPRISE_ID)
VALUES
('2', '21%', 1, null);

-- taxes versions
INSERT INTO RF_COMMONS_TAXES_VERSIONS
(COMMON_TAX_ID, START_DATE, RATE, BUSINESS_CUSTOMER_ID, ENTERPRISE_ID)
VALUES
((SELECT ID FROM RF_COMMONS_TAXES WHERE CODE = '2' AND BUSINESS_CUSTOMER_ID = 1), '2000-01-01', 21, 1, null);



