-- Tabla de clientes
CREATE TABLE IF NOT EXISTS RF_ACCOUNTING_ACCOUNTING(
ID int AUTO_INCREMENT primary key,
CODE varchar(10),
NAME varchar(30),
USER_CREATED_AT_ID int,
USER_UPDATED_AT_ID int,
CREATED_AT DATETIME,
UPDATED_AT DATETIME
);